# Generated by Django 3.2.4 on 2021-08-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegirHorarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='descripcion',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
