# Generated by Django 3.2.4 on 2021-08-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegirHorarios', '0002_alter_opcion_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='estado',
        ),
    ]
