# Generated by Django 3.2.4 on 2021-09-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegirHorarios', '0003_remove_opcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='descripcion',
            field=models.CharField(max_length=1),
        ),
    ]
