# Generated by Django 3.2.4 on 2021-07-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegirHorarios', '0004_auto_20210727_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
