# Generated by Django 3.2.4 on 2021-07-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elegirHorarios', '0005_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
