# Generated by Django 3.2.4 on 2021-07-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elegirHorarios', '0006_auto_20210727_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionhorario',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='opcionhorario',
            name='hora_inicio',
        ),
    ]
