# Generated by Django 3.2.4 on 2021-08-01 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elegirHorarios', '0008_auto_20210730_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='profesor',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horario',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='id_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elegirHorarios.curso'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='id_profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elegirHorarios.profesor'),
        ),
        migrations.AlterField(
            model_name='opciondia',
            name='id_dia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='elegirHorarios.dia'),
        ),
        migrations.AlterField(
            model_name='opciondia',
            name='id_opcion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='elegirHorarios.opcion'),
        ),
        migrations.AlterField(
            model_name='opcionhorario',
            name='id_horario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='elegirHorarios.horario'),
        ),
        migrations.AlterField(
            model_name='opcionhorario',
            name='id_opcion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='elegirHorarios.opcion'),
        ),
    ]
